version: "3.9"

services:
  database:
    image: postgres
    container_name: database_restaurant-api
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=digitalhouse
      - POSTGRES_DB=restaurant-api
    volumes:
      - pgdata:/data/postgres

volumes: 
  pgdata: 
    driver: local
