name: CI

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          version: 14.x
          
      - name: Install Dependencies
        run: yarn
        
      - name: Build
        run: yarn build
        
      - uses: fifsky/ssh-action@master
        with:
          command: |
            ls -a
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSS_USER }}
          key: ${{ secrets.SSH_KEY }}
          
